import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.digifamar.app",
  appName: "DiGiFaMaR",
  webDir: "dist/client",
  // The app is SSR (TanStack Start), so the WebView loads the live hosted site
  // rather than static bundled assets. dist/client/index.html (generated by
  // scripts/capacitor-web-shell.mjs) is only a sync placeholder / loading shell.
  server: {
    url: "https://app.digifamar.com",
    cleartext: false,
  },
};

export default config;
