/**
 * Per-listing Open Graph / Twitter card images.
 *
 * Generated by `scripts/og-listing-cards.py` (1200x630, rendered at 2x and
 * downsampled) and uploaded to the CDN. Each card embeds the latest v10 logo,
 * the listing photo and the listing's own details.
 */
import og_farm_blue_ridge from "@/assets/og/og-farm-blue-ridge.jpg.asset.json";
import og_farm_golden_meadow from "@/assets/og/og-farm-golden-meadow.jpg.asset.json";
import og_farm_homestead_hollow from "@/assets/og/og-farm-homestead-hollow.jpg.asset.json";
import og_farm_morning_glory from "@/assets/og/og-farm-morning-glory.jpg.asset.json";
import og_farm_river_bend from "@/assets/og/og-farm-river-bend.jpg.asset.json";
import og_farm_sunrise_orchards from "@/assets/og/og-farm-sunrise-orchards.jpg.asset.json";
import og_product_creamline_milk from "@/assets/og/og-product-creamline-milk.jpg.asset.json";
import og_product_grass_fed_ribeye from "@/assets/og/og-product-grass-fed-ribeye.jpg.asset.json";
import og_product_heirloom_tomatoes from "@/assets/og/og-product-heirloom-tomatoes.jpg.asset.json";
import og_product_honeycrisp_apples from "@/assets/og/og-product-honeycrisp-apples.jpg.asset.json";
import og_product_pasture_eggs from "@/assets/og/og-product-pasture-eggs.jpg.asset.json";
import og_product_peach_preserves from "@/assets/og/og-product-peach-preserves.jpg.asset.json";
import og_product_salad_mix from "@/assets/og/og-product-salad-mix.jpg.asset.json";
import og_product_wildflower_honey from "@/assets/og/og-product-wildflower-honey.jpg.asset.json";
import { abs, BRAND } from "@/lib/brand";

const FARM_CARDS: Record<string, string> = {
  "blue-ridge": og_farm_blue_ridge.url,
  "golden-meadow": og_farm_golden_meadow.url,
  "homestead-hollow": og_farm_homestead_hollow.url,
  "morning-glory": og_farm_morning_glory.url,
  "river-bend": og_farm_river_bend.url,
  "sunrise-orchards": og_farm_sunrise_orchards.url,
};

const PRODUCT_CARDS: Record<string, string> = {
  "creamline-milk": og_product_creamline_milk.url,
  "grass-fed-ribeye": og_product_grass_fed_ribeye.url,
  "heirloom-tomatoes": og_product_heirloom_tomatoes.url,
  "honeycrisp-apples": og_product_honeycrisp_apples.url,
  "pasture-eggs": og_product_pasture_eggs.url,
  "peach-preserves": og_product_peach_preserves.url,
  "salad-mix": og_product_salad_mix.url,
  "wildflower-honey": og_product_wildflower_honey.url,
};

/** Absolute (crawler-safe) card URL for a farm listing. */
export const farmOgImage = (id: string) => (FARM_CARDS[id] ? abs(FARM_CARDS[id]) : BRAND.og.market);

/** Absolute (crawler-safe) card URL for a product listing. */
export const productOgImage = (id: string) =>
  PRODUCT_CARDS[id] ? abs(PRODUCT_CARDS[id]) : BRAND.og.market;

export const OG_CARD_WIDTH = 1200;
export const OG_CARD_HEIGHT = 630;
