/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HacksRouteImport } from './routes/hacks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuyerProtectionRouteImport } from './routes/buyer-protection'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignupFarmerRouteImport } from './routes/signup.farmer'
import { Route as SignupBuyerRouteImport } from './routes/signup.buyer'
import { Route as SettingsMapsRouteImport } from './routes/settings.maps'
import { Route as SettingsDeleteAccountRouteImport } from './routes/settings.delete-account'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as LendersLoginRouteImport } from './routes/lenders/login'
import { Route as LendersDashboardRouteImport } from './routes/lenders/dashboard'
import { Route as LendersApplyRouteImport } from './routes/lenders/apply'
import { Route as LendersAdminRouteImport } from './routes/lenders/admin'
import { Route as FarmIdRouteImport } from './routes/farm.$id'
import { Route as DashboardFarmerRouteImport } from './routes/dashboard.farmer'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard.buyer'
import { Route as ChatProductIdRouteImport } from './routes/chat.$productId'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as LendersFarmerIdRouteImport } from './routes/lenders/farmer.$id'
import { Route as ChatFarmFarmIdRouteImport } from './routes/chat.farm.$farmId'
import { Route as ApiPublicCronAutoReleaseRouteImport } from './routes/api/public/cron/auto-release'
import { Route as ApiOrdersIdReleaseRouteImport } from './routes/api/orders.$id.release'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HacksRoute = HacksRouteImport.update({
  id: '/hacks',
  path: '/hacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProtectionRoute = BuyerProtectionRouteImport.update({
  id: '/buyer-protection',
  path: '/buyer-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupFarmerRoute = SignupFarmerRouteImport.update({
  id: '/signup/farmer',
  path: '/signup/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupBuyerRoute = SignupBuyerRouteImport.update({
  id: '/signup/buyer',
  path: '/signup/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMapsRoute = SettingsMapsRouteImport.update({
  id: '/settings/maps',
  path: '/settings/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDeleteAccountRoute = SettingsDeleteAccountRouteImport.update({
  id: '/settings/delete-account',
  path: '/settings/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersLoginRoute = LendersLoginRouteImport.update({
  id: '/lenders/login',
  path: '/lenders/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersDashboardRoute = LendersDashboardRouteImport.update({
  id: '/lenders/dashboard',
  path: '/lenders/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersApplyRoute = LendersApplyRouteImport.update({
  id: '/lenders/apply',
  path: '/lenders/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersAdminRoute = LendersAdminRouteImport.update({
  id: '/lenders/admin',
  path: '/lenders/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmIdRoute = FarmIdRouteImport.update({
  id: '/farm/$id',
  path: '/farm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFarmerRoute = DashboardFarmerRouteImport.update({
  id: '/dashboard/farmer',
  path: '/dashboard/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatProductIdRoute = ChatProductIdRouteImport.update({
  id: '/chat/$productId',
  path: '/chat/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/admin/maps',
  path: '/admin/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersFarmerIdRoute = LendersFarmerIdRouteImport.update({
  id: '/lenders/farmer/$id',
  path: '/lenders/farmer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFarmFarmIdRoute = ChatFarmFarmIdRouteImport.update({
  id: '/chat/farm/$farmId',
  path: '/chat/farm/$farmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutoReleaseRoute =
  ApiPublicCronAutoReleaseRouteImport.update({
    id: '/api/public/cron/auto-release',
    path: '/api/public/cron/auto-release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersIdReleaseRoute = ApiOrdersIdReleaseRouteImport.update({
  id: '/$id/release',
  path: '/$id/release',
  getParentRoute: () => ApiOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hacks': typeof HacksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending': typeof LendingRoute
  '/market': typeof MarketRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/chat/$productId': typeof ChatProductIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/farm/$id': typeof FarmIdRoute
  '/lenders/admin': typeof LendersAdminRoute
  '/lenders/apply': typeof LendersApplyRoute
  '/lenders/dashboard': typeof LendersDashboardRoute
  '/lenders/login': typeof LendersLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/maps': typeof SettingsMapsRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/farmer': typeof SignupFarmerRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/chat/farm/$farmId': typeof ChatFarmFarmIdRoute
  '/lenders/farmer/$id': typeof LendersFarmerIdRoute
  '/api/orders/$id/release': typeof ApiOrdersIdReleaseRoute
  '/api/public/cron/auto-release': typeof ApiPublicCronAutoReleaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hacks': typeof HacksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending': typeof LendingRoute
  '/market': typeof MarketRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/chat/$productId': typeof ChatProductIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/farm/$id': typeof FarmIdRoute
  '/lenders/admin': typeof LendersAdminRoute
  '/lenders/apply': typeof LendersApplyRoute
  '/lenders/dashboard': typeof LendersDashboardRoute
  '/lenders/login': typeof LendersLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/maps': typeof SettingsMapsRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/farmer': typeof SignupFarmerRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/signup': typeof SignupIndexRoute
  '/chat/farm/$farmId': typeof ChatFarmFarmIdRoute
  '/lenders/farmer/$id': typeof LendersFarmerIdRoute
  '/api/orders/$id/release': typeof ApiOrdersIdReleaseRoute
  '/api/public/cron/auto-release': typeof ApiPublicCronAutoReleaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/buyer-protection': typeof BuyerProtectionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/hacks': typeof HacksRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending': typeof LendingRoute
  '/market': typeof MarketRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/maps': typeof AdminMapsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/chat/$productId': typeof ChatProductIdRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/farm/$id': typeof FarmIdRoute
  '/lenders/admin': typeof LendersAdminRoute
  '/lenders/apply': typeof LendersApplyRoute
  '/lenders/dashboard': typeof LendersDashboardRoute
  '/lenders/login': typeof LendersLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/settings/delete-account': typeof SettingsDeleteAccountRoute
  '/settings/maps': typeof SettingsMapsRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/farmer': typeof SignupFarmerRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/chat/farm/$farmId': typeof ChatFarmFarmIdRoute
  '/lenders/farmer/$id': typeof LendersFarmerIdRoute
  '/api/orders/$id/release': typeof ApiOrdersIdReleaseRoute
  '/api/public/cron/auto-release': typeof ApiPublicCronAutoReleaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/buyer-protection'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/hacks'
    | '/how-it-works'
    | '/lending'
    | '/market'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/maps'
    | '/api/orders'
    | '/chat/$productId'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/farm/$id'
    | '/lenders/admin'
    | '/lenders/apply'
    | '/lenders/dashboard'
    | '/lenders/login'
    | '/orders/$id'
    | '/product/$id'
    | '/settings/delete-account'
    | '/settings/maps'
    | '/signup/buyer'
    | '/signup/farmer'
    | '/admin/'
    | '/chat/'
    | '/orders/'
    | '/signup/'
    | '/chat/farm/$farmId'
    | '/lenders/farmer/$id'
    | '/api/orders/$id/release'
    | '/api/public/cron/auto-release'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/buyer-protection'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/hacks'
    | '/how-it-works'
    | '/lending'
    | '/market'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/maps'
    | '/api/orders'
    | '/chat/$productId'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/farm/$id'
    | '/lenders/admin'
    | '/lenders/apply'
    | '/lenders/dashboard'
    | '/lenders/login'
    | '/orders/$id'
    | '/product/$id'
    | '/settings/delete-account'
    | '/settings/maps'
    | '/signup/buyer'
    | '/signup/farmer'
    | '/admin'
    | '/chat'
    | '/orders'
    | '/signup'
    | '/chat/farm/$farmId'
    | '/lenders/farmer/$id'
    | '/api/orders/$id/release'
    | '/api/public/cron/auto-release'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/browse'
    | '/buyer-protection'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/hacks'
    | '/how-it-works'
    | '/lending'
    | '/market'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/maps'
    | '/api/orders'
    | '/chat/$productId'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/farm/$id'
    | '/lenders/admin'
    | '/lenders/apply'
    | '/lenders/dashboard'
    | '/lenders/login'
    | '/orders/$id'
    | '/product/$id'
    | '/settings/delete-account'
    | '/settings/maps'
    | '/signup/buyer'
    | '/signup/farmer'
    | '/admin/'
    | '/chat/'
    | '/orders/'
    | '/signup/'
    | '/chat/farm/$farmId'
    | '/lenders/farmer/$id'
    | '/api/orders/$id/release'
    | '/api/public/cron/auto-release'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  BuyerProtectionRoute: typeof BuyerProtectionRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HacksRoute: typeof HacksRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LendingRoute: typeof LendingRoute
  MarketRoute: typeof MarketRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminMapsRoute: typeof AdminMapsRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ChatProductIdRoute: typeof ChatProductIdRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardFarmerRoute: typeof DashboardFarmerRoute
  FarmIdRoute: typeof FarmIdRoute
  LendersAdminRoute: typeof LendersAdminRoute
  LendersApplyRoute: typeof LendersApplyRoute
  LendersDashboardRoute: typeof LendersDashboardRoute
  LendersLoginRoute: typeof LendersLoginRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  SettingsDeleteAccountRoute: typeof SettingsDeleteAccountRoute
  SettingsMapsRoute: typeof SettingsMapsRoute
  SignupBuyerRoute: typeof SignupBuyerRoute
  SignupFarmerRoute: typeof SignupFarmerRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ChatFarmFarmIdRoute: typeof ChatFarmFarmIdRoute
  LendersFarmerIdRoute: typeof LendersFarmerIdRoute
  ApiPublicCronAutoReleaseRoute: typeof ApiPublicCronAutoReleaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacks': {
      id: '/hacks'
      path: '/hacks'
      fullPath: '/hacks'
      preLoaderRoute: typeof HacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-protection': {
      id: '/buyer-protection'
      path: '/buyer-protection'
      fullPath: '/buyer-protection'
      preLoaderRoute: typeof BuyerProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/farmer': {
      id: '/signup/farmer'
      path: '/signup/farmer'
      fullPath: '/signup/farmer'
      preLoaderRoute: typeof SignupFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/buyer': {
      id: '/signup/buyer'
      path: '/signup/buyer'
      fullPath: '/signup/buyer'
      preLoaderRoute: typeof SignupBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/maps': {
      id: '/settings/maps'
      path: '/settings/maps'
      fullPath: '/settings/maps'
      preLoaderRoute: typeof SettingsMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/delete-account': {
      id: '/settings/delete-account'
      path: '/settings/delete-account'
      fullPath: '/settings/delete-account'
      preLoaderRoute: typeof SettingsDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/login': {
      id: '/lenders/login'
      path: '/lenders/login'
      fullPath: '/lenders/login'
      preLoaderRoute: typeof LendersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/dashboard': {
      id: '/lenders/dashboard'
      path: '/lenders/dashboard'
      fullPath: '/lenders/dashboard'
      preLoaderRoute: typeof LendersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/apply': {
      id: '/lenders/apply'
      path: '/lenders/apply'
      fullPath: '/lenders/apply'
      preLoaderRoute: typeof LendersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/admin': {
      id: '/lenders/admin'
      path: '/lenders/admin'
      fullPath: '/lenders/admin'
      preLoaderRoute: typeof LendersAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/$id': {
      id: '/farm/$id'
      path: '/farm/$id'
      fullPath: '/farm/$id'
      preLoaderRoute: typeof FarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/farmer': {
      id: '/dashboard/farmer'
      path: '/dashboard/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof DashboardFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$productId': {
      id: '/chat/$productId'
      path: '/chat/$productId'
      fullPath: '/chat/$productId'
      preLoaderRoute: typeof ChatProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/admin/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/farmer/$id': {
      id: '/lenders/farmer/$id'
      path: '/lenders/farmer/$id'
      fullPath: '/lenders/farmer/$id'
      preLoaderRoute: typeof LendersFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/farm/$farmId': {
      id: '/chat/farm/$farmId'
      path: '/chat/farm/$farmId'
      fullPath: '/chat/farm/$farmId'
      preLoaderRoute: typeof ChatFarmFarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-release': {
      id: '/api/public/cron/auto-release'
      path: '/api/public/cron/auto-release'
      fullPath: '/api/public/cron/auto-release'
      preLoaderRoute: typeof ApiPublicCronAutoReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$id/release': {
      id: '/api/orders/$id/release'
      path: '/$id/release'
      fullPath: '/api/orders/$id/release'
      preLoaderRoute: typeof ApiOrdersIdReleaseRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
  }
}

interface ApiOrdersRouteChildren {
  ApiOrdersIdReleaseRoute: typeof ApiOrdersIdReleaseRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersIdReleaseRoute: ApiOrdersIdReleaseRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  BuyerProtectionRoute: BuyerProtectionRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HacksRoute: HacksRoute,
  HowItWorksRoute: HowItWorksRoute,
  LendingRoute: LendingRoute,
  MarketRoute: MarketRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminMapsRoute: AdminMapsRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ChatProductIdRoute: ChatProductIdRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardFarmerRoute: DashboardFarmerRoute,
  FarmIdRoute: FarmIdRoute,
  LendersAdminRoute: LendersAdminRoute,
  LendersApplyRoute: LendersApplyRoute,
  LendersDashboardRoute: LendersDashboardRoute,
  LendersLoginRoute: LendersLoginRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  SettingsDeleteAccountRoute: SettingsDeleteAccountRoute,
  SettingsMapsRoute: SettingsMapsRoute,
  SignupBuyerRoute: SignupBuyerRoute,
  SignupFarmerRoute: SignupFarmerRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  ChatFarmFarmIdRoute: ChatFarmFarmIdRoute,
  LendersFarmerIdRoute: LendersFarmerIdRoute,
  ApiPublicCronAutoReleaseRoute: ApiPublicCronAutoReleaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
